Upgrade upstream 1.4.0 rdmo 1.6.0
FDM-UARuhr/rdmo-catalog-uaruhr pull request #118
Opened 2023-12-21 11:28 UTC by kaprz001

Fixes #issuenumber ; refs #issuenumber

Present tense short summary (50 characters or less)

More detailed description, if necessary. Try to be as descriptive as you can: even if you think that the PR content is obvious, it may not be obvious to others. Include tracebacks if helpful, and be sure to call out any bits of the PR that may be work-in-progress.

Description can have multiple paragraphs and you can use code examples inside:

``` ruby
class PostsController
  def index
    respond_with Post.limit(10)
  end
end
```

Changes proposed in this pull request:
*
*
*

@FDM-UARuhr/Reviewers

2024-02-03 08:32 UTC, HenningTimm requested changes
Hab gerade einmal drüber geguckt. Eine Inkonsistenz ist mir aufgefallen. Wir scheinen den Eintrga Infrastructure Resources in rdmorganizer/options/rdmo.xml doppelt zu haben. Das kann aber sein, dass der Fehler schon vom letzten Mal ist. Das sollten wir auf jeden Fall aufräumen.

2024-02-03 08:32 UTC, HenningTimm commented on rdmorganiser/options/rdmo.xml
Hier passen die Zeilennummern nicht zu dem was ich in Upstream sehe. Es sieht so aus als hätten wir `https://rdmorganiser.github.io/terms/options/infrastructure_resources/262` zwei mal drin. Das kommt glaube ich nicht aus diesem PR, sollte aber trotzdem glaube ich nicht sein.

2024-02-03 08:32 UTC, HenningTimm commented on rdmorganiser/questions/horizon-europe.xml
> +		<help lang="de">Dieser Katalog ist für Forschungsprojekte bestimmt, die durch die Europäische Kommission im Förderprogramm  Horizon Europe finanziert werden. Er ist nach der &lt;a href="https://ec.
Ahhh, ein doppeltes Leerzeichen von Upstream (zwischen Förderprogramm und Horizon)! Würde ich glaube ich so lassen, um keine Inkonsistenz zu erzeugen.

2024-02-16 12:23 UTC, jmfrenzel commented on rdmorganiser/options/rdmo.xml
resolved by  https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/pull/118/commits/313d3ff2eb5661d44455beeeb758470029a9e5bc

2024-02-16 17:14 UTC, HenningTimm approved these changes

2025-04-04 09:24 UTC, merged